name: Build SBA APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        # This command forces the install even if there are small conflicts
        run: npm install --legacy-peer-deps

      - name: 🚀 Build APK Locally
        run: npx eas-cli build --platform android --profile production --local --non-interactive
