name: Build SBA APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install --legacy-peer-deps

      - name: 🚀 Build APK Locally
        run: npx eas-cli build --platform android --profile production --local --non-interactive

      - name: 🔍 Find and Rename APK
        # This part looks for any .apk file and renames it to a simple name
        run: find . -name "*.apk" -exec mv {} sba-app.apk \;

      - name: 📤 Upload APK for Download
        uses: actions/upload-artifact@v4
        with:
          name: SBA-Accounts-App
          path: sba-app.apk
